# model
model_name: 'DSIFNet'
pretrained: None
head_pretrained: False
loss_name: 'deep_ce_dice'
n_class: 1

# data
num_workers: 4
batch_size: 8
dataset: 'CDDataset'
data_name: 'LEVIR'
split: 'train'
split_val: 'val'
img_size: 256
val_data_norm: True
with_dataset_aug: True

# optimize
optim_mode: 'adam'
lr: 0.0001
lr_policy: 'exp'
max_epochs: 100
