# model
model_name: 'STANet'
pretrained: 'imagenet'
head_pretrained: False
loss_name: 'bcl'
n_class: 1

# data
num_workers: 4
batch_size: 4
dataset: 'CDDataset'
data_name: 'LEVIR'
split: 'train'
split_val: 'val'
img_size: 256
val_data_norm: True
with_dataset_aug: True

# optimize
optim_mode: 'adam'
lr: 0.001
lr_policy: "linear"
max_epochs: 200
