# model
model_name: 'SUNet'
pretrained: None
head_pretrained: False
loss_name: 'ce_iou'
n_class: 2

# data
num_workers: 4
batch_size: 8
dataset: 'CDDataset'
data_name: 'LEVIR'
split: 'train'
split_val: 'val'
img_size: 256
val_data_norm: True
with_dataset_aug: True
with_origin_scale_ret: 3

# optimize
optim_mode: 'sgd'
lr: 0.005
lr_policy: "linear"
max_epochs: 200
